name: doc-to-markdown-dev

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ../frontend/src:/app/src
    environment:
      - NODE_ENV=development
      - API_KEY=${API_KEY}
      - RATE_LIMIT=${RATE_LIMIT:-60}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    networks:
      - app-network
    volumes:
      - ../backend/app:/app/app
      - ../backend/tests/fixtures:/app/tests/fixtures:ro
      - doc-to-markdown-tmp:/tmp/doc-to-markdown
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
      - API_KEY=${API_KEY}
      - RATE_LIMIT=${RATE_LIMIT:-60}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

networks:
  app-network:
    driver: bridge

volumes:
  doc-to-markdown-tmp:
