name: magic-markdown

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    environment:
      # Add your api key below (required)
      - API_KEY=
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nginx/index.html"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    environment:
      - API_KEY= # Add your API key here (required)
      - RATE_LIMIT=60 # Change rate limit (optional)
    networks:
      - app-network
    volumes:
      - ../backend/tests/fixtures:/app/tests/fixtures:ro
      - magic-markdown-tmp:/tmp/doc-to-markdown
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nginx/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  app-network:
    driver: bridge

volumes:
  magic-markdown-tmp:
