version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/index.html"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8001:8001"
    networks:
      - app-network
    volumes:
      - ../backend/tests/fixtures:/app/tests/fixtures:ro
      - doc-to-markdown-tmp:/tmp/doc-to-markdown
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge

volumes:
  doc-to-markdown-tmp: