version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ../frontend/src:/app/src
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    networks:
      - app-network
    volumes:
      - ../backend/app:/app/app
      - ../backend/tests/fixtures:/app/tests/fixtures:ro
      - doc-to-markdown-tmp:/tmp/doc-to-markdown
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

networks:
  app-network:
    driver: bridge

volumes:
  doc-to-markdown-tmp: