name: doc-to-markdown

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/index.html"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - MARKDOWN_API_KEY=${MARKDOWN_API_KEY:-your-secret-key-here}  # Set this in production
      - MARKDOWN_ALLOWED_ORIGINS=${MARKDOWN_ALLOWED_ORIGINS:-http://localhost:8000}
      - MARKDOWN_RATE_LIMIT_PER_MINUTE=${MARKDOWN_RATE_LIMIT_PER_MINUTE:-60}
    networks:
      - app-network
    volumes:
      - ../backend/tests/fixtures:/app/tests/fixtures:ro
      - doc-to-markdown-tmp:/tmp/doc-to-markdown
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  app-network:
    driver: bridge

volumes:
  doc-to-markdown-tmp: