name: doc-to-markdown-ci

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/index.html"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    networks:
      - app-network
    volumes:
      - ../backend/tests/fixtures:/app/tests/fixtures:ro
      - doc-to-markdown-tmp:/tmp/doc-to-markdown
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  app-network:
    driver: bridge

volumes:
  doc-to-markdown-tmp: