name: Docker Build and Test

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/**'
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/docker.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'docker/**'
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/docker.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build development containers
        run: |
          cd docker
          docker compose -f docker-compose.dev.yml build

      - name: Start development containers
        run: |
          cd docker
          docker compose -f docker-compose.dev.yml up -d

      - name: Wait for services to start
        run: sleep 10

      - name: Check frontend health
        run: |
          curl -f http://localhost:8000/index.html || exit 1

      - name: Check backend health
        run: |
          curl -f http://localhost:8001/api/health || exit 1

      - name: Test file conversion
        run: |
          cd backend/tests/fixtures
          curl -X POST -F "file=@sample.docx" http://localhost:8001/api/v1/convert

      - name: Build production containers
        run: |
          cd docker
          docker compose build

      - name: Start production containers
        run: |
          cd docker
          docker compose up -d

      - name: Wait for services to start
        run: sleep 10

      - name: Check frontend health (production)
        run: |
          curl -f http://localhost:8000/index.html || exit 1

      - name: Check backend health (production)
        run: |
          curl -f http://localhost:8001/api/health || exit 1

      - name: Stop containers
        run: |
          cd docker
          docker compose down
          docker compose -f docker-compose.dev.yml down