name: Docker Build and Test

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/**'
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/docker.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'docker/**'
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/docker.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Build development containers
        run: docker compose -f docker/docker-compose.dev.yml build

      - name: Start development containers
        run: docker compose -f docker/docker-compose.dev.yml up -d

      - name: Wait for services to start
        run: |
          echo "Waiting for backend to be healthy..."
          timeout 30s bash -c 'until curl -s http://localhost:8001/api/health; do sleep 1; done'
          echo "Waiting for frontend to be ready..."
          timeout 30s bash -c 'until curl -s http://localhost:8000/index.html; do sleep 1; done'

      - name: Test file conversion
        run: |
          cd backend/tests/fixtures
          curl -X POST -F "file=@sample.docx" http://localhost:8001/api/v1/convert

      - name: Build production containers
        run: docker compose -f docker/docker-compose.yml build

      - name: Start production containers
        run: docker compose -f docker/docker-compose.yml up -d

      - name: Wait for services to start
        run: |
          echo "Waiting for backend to be healthy..."
          timeout 30s bash -c 'until curl -s http://localhost:8001/api/health; do sleep 1; done'
          echo "Waiting for frontend to be ready..."
          timeout 30s bash -c 'until curl -s http://localhost:8000/index.html; do sleep 1; done'

      - name: Test file conversion (production)
        run: |
          cd backend/tests/fixtures
          curl -X POST -F "file=@sample.docx" http://localhost:8001/api/v1/convert

      - name: Stop containers
        if: always()
        run: |
          docker compose -f docker/docker-compose.yml down
          docker compose -f docker/docker-compose.dev.yml down